services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ${NPM_DATA_VOLUME}/data:/data
      - ${NPM_DATA_VOLUME}/letsencrypt:/etc/letsencrypt
####
#
#     Default Administrator User login:
#     Email:    admin@example.com
#     Password: changeme
#
####
